"""The deterministic Fallback Planner (design §16.4). ARCHITECTURE_CONTRACTS.md
§10: "A Fallback Planner must always exist and must always satisfy the hard
rules (ignoring soft rules if necessary) -- a demo/run can never fail to
produce a plan." Called by the G2 Planning graph whenever the Planner Agent
is degraded (no LLM provider configured -- this project's default) or its
draft still fails deterministic validation after
`PLANNER_MAX_DRAFT_ATTEMPTS` retries.

A pure function -- no DB/gateway import anywhere in this module, same shape
as `app/planning/validator.py` and `app/gap/engine.py`. Reasons are
templated ("plan_with_generic_reasons()" per design §16.4), never LLM-phrased
-- that is exactly what distinguishes this path from the Planner Agent's.
"""
from __future__ import annotations

import uuid

from app.core.thresholds import (
    NEW_SKILL_CONCURRENCY_CAP,
    PRACTICE_ITEM_MINUTES_PER_ITEM,
    PRACTICE_ITEMS_PER_LESSON,
    PROBE_ITEM_COUNT,
    PROBE_ITEM_MINUTES_PER_ITEM,
)
from app.gap.engine import SkillGapEntry
from app.planning.candidates import ObjectiveCandidateSet
from app.schemas.common import PlanItem, PlanItemReason

FALLBACK_OVERALL_REASON = (
    "Generated by the deterministic fallback planner: objectives ordered by priority "
    "and prerequisite layer, budget-fit greedily, no LLM narration."
)


def _difficulty_for(cs: ObjectiveCandidateSet) -> int:
    # design §17.2 V4: difficulty <= current_level(skill) + 1.
    return max(1, min(cs.target_level, cs.current_level + 1))


def _new_item_id() -> str:
    return str(uuid.uuid4())


def build_fallback_plan(
    candidate_sets: dict[str, ObjectiveCandidateSet],
    *,
    gaps_by_skill: dict[str, SkillGapEntry],
    hours_budget_minutes: float,
    new_skill_cap: int = NEW_SKILL_CONCURRENCY_CAP,
    num_days: int = 5,
) -> list[PlanItem]:
    """design §16.4's `frontier -> greedy budget-fit loop`, adapted to this
    project's data shapes. `candidate_sets` values are ordered by priority
    (desc) then `ordering_layer` (asc, topological -- design's "then
    topological layer") before scheduling. An objective with an empty
    candidate set (no eligible resources for a lesson, no bank items for a
    probe) is simply skipped -- this is what makes an "impossible candidate
    set" still resolve to a valid (possibly empty) plan rather than an
    error, per ARCHITECTURE_CONTRACTS.md §10.
    """

    def _sort_key(cs: ObjectiveCandidateSet) -> tuple[float, int]:
        gap = gaps_by_skill.get(cs.skill_id)
        layer = gap.ordering_layer if gap is not None and gap.ordering_layer >= 0 else 10_000
        return (-cs.priority, layer)

    frontier = sorted(candidate_sets.values(), key=_sort_key)

    items: list[PlanItem] = []
    minutes = 0.0
    new_skills: set[str] = set()
    day = 1

    for cs in frontier:
        if cs.objective_type == "probe":
            probe_ids = cs.practice_item_ids[:PROBE_ITEM_COUNT]
            if not probe_ids:
                continue
            est = PROBE_ITEM_MINUTES_PER_ITEM * len(probe_ids)
            if minutes + est > hours_budget_minutes:
                continue
            items.append(
                PlanItem(
                    item_id=_new_item_id(),
                    type="probe",
                    objective_id=cs.objective_id,
                    skill_id=cs.skill_id,
                    resource_id=None,
                    practice_item_ids=probe_ids,
                    est_minutes=est,
                    difficulty=1,
                    day_slot=day,
                    depends_on=[],
                    reason=PlanItemReason(
                        text=f"Verify-before-teach probe for {cs.skill_id}: confirm what you already know first."
                    ),
                )
            )
            minutes += est
            day = day % num_days + 1
            continue

        if cs.skill_id not in new_skills and len(new_skills) >= new_skill_cap:
            continue
        if not cs.resources:
            continue

        res = cs.resources[0]  # already ranked best-first, eligibility-filtered (Phase 6)
        practice_ids = cs.practice_item_ids[:PRACTICE_ITEMS_PER_LESSON]
        practice_minutes = PRACTICE_ITEM_MINUTES_PER_ITEM * len(practice_ids)
        need = res.duration_min + practice_minutes
        if minutes + need > hours_budget_minutes:
            continue  # design: "try smaller resource / next objective" -- next objective, kept simple

        difficulty = _difficulty_for(cs)
        items.append(
            PlanItem(
                item_id=_new_item_id(),
                type="resource",
                objective_id=cs.objective_id,
                skill_id=cs.skill_id,
                resource_id=res.resource_id,
                practice_item_ids=[],
                est_minutes=res.duration_min,
                difficulty=difficulty,
                day_slot=day,
                depends_on=[],
                reason=PlanItemReason(text=f"{res.title} -- selected for objective {cs.objective_id} (fallback planner)."),
            )
        )
        minutes += res.duration_min
        new_skills.add(cs.skill_id)

        if practice_ids:
            items.append(
                PlanItem(
                    item_id=_new_item_id(),
                    type="practice",
                    objective_id=cs.objective_id,
                    skill_id=cs.skill_id,
                    resource_id=None,
                    practice_item_ids=practice_ids,
                    est_minutes=practice_minutes,
                    difficulty=difficulty,
                    day_slot=day,
                    depends_on=[],
                    reason=PlanItemReason(text=f"Practice for {cs.skill_id}, paired with the resource above."),
                )
            )
            minutes += practice_minutes

        day = day % num_days + 1

    return items
