"""The deterministic Fallback Planner (design §16.4). ARCHITECTURE_CONTRACTS.md
§10: "A Fallback Planner must always exist and must always satisfy the hard
rules (ignoring soft rules if necessary) -- a demo/run can never fail to
produce a plan." Called by the G2 Planning graph whenever the Planner Agent
is degraded (no LLM provider configured -- this project's default) or its
draft still fails deterministic validation after
`PLANNER_MAX_DRAFT_ATTEMPTS` retries.

A pure function -- no DB/gateway import anywhere in this module, same shape
as `app/planning/validator.py` and `app/gap/engine.py`. Reasons are
templated ("plan_with_generic_reasons()" per design §16.4), never LLM-phrased
-- that is exactly what distinguishes this path from the Planner Agent's.

Stage 2 (`docs/RESOURCE_SESSIONIZATION.md`): the planner understands *resource
sessions*. Phase A (breadth) is design §16.4's loop unchanged -- one unit per
objective, now "the first study session of the best resource" (a whole short
resource is one complete session); Phase B (depth) continues the objectives
already in the plan with their next in-order sessions / next-ranked resources
(`app/planning/fill.py::extend_plan`) up to an *acceptable* utilization, never
past the budget and never onto a new skill. A provider failure therefore no
longer reintroduces the thin-plan problem, and no hard rule is relaxed."""
from __future__ import annotations

import uuid

from app.core.thresholds import (
    NEW_SKILL_CONCURRENCY_CAP,
    PLAN_MAX_RESOURCES_PER_OBJECTIVE,
    PLAN_TARGET_UTILIZATION,
    PRACTICE_ITEM_MINUTES_PER_ITEM,
    PRACTICE_ITEMS_PER_LESSON,
    PROBE_ITEM_COUNT,
    PROBE_ITEM_MINUTES_PER_ITEM,
)
from app.gap.engine import SkillGapEntry
from app.planning.candidates import ObjectiveCandidateSet
from app.planning.fill import DayPlanner, difficulty_for, extend_plan, session_item
from app.schemas.common import PlanItem, PlanItemReason

FALLBACK_OVERALL_REASON = (
    "Generated by the deterministic fallback planner: objectives ordered by priority "
    "and prerequisite layer, budget-fit greedily, no LLM narration."
)


def _new_item_id() -> str:
    return str(uuid.uuid4())


def build_fallback_plan(
    candidate_sets: dict[str, ObjectiveCandidateSet],
    *,
    gaps_by_skill: dict[str, SkillGapEntry],
    hours_budget_minutes: float,
    new_skill_cap: int = NEW_SKILL_CONCURRENCY_CAP,
    num_days: int = 5,
    target_utilization: float = PLAN_TARGET_UTILIZATION,
    max_resources_per_objective: int = PLAN_MAX_RESOURCES_PER_OBJECTIVE,
) -> list[PlanItem]:
    """design §16.4's `frontier -> greedy budget-fit loop`, adapted to this
    project's data shapes. `candidate_sets` values are ordered by priority
    (desc) then `ordering_layer` (asc, topological -- design's "then
    topological layer") before scheduling. An objective with an empty
    candidate set (no eligible resources for a lesson, no bank items for a
    probe) is simply skipped -- this is what makes an "impossible candidate
    set" still resolve to a valid (possibly empty) plan rather than an
    error, per ARCHITECTURE_CONTRACTS.md §10.
    """

    def _sort_key(cs: ObjectiveCandidateSet) -> tuple[float, int]:
        gap = gaps_by_skill.get(cs.skill_id)
        layer = gap.ordering_layer if gap is not None and gap.ordering_layer >= 0 else 10_000
        return (-cs.priority, layer)

    frontier = sorted(candidate_sets.values(), key=_sort_key)

    items: list[PlanItem] = []
    minutes = 0.0
    new_skills: set[str] = set()
    used_resources: set[str] = set()  # a resource targeting two objectives' skills is studied once, under the higher-priority one
    days = DayPlanner(hours_budget_minutes=hours_budget_minutes, num_days=num_days, target_utilization=target_utilization)

    for cs in frontier:
        if cs.objective_type == "probe":
            probe_ids = cs.practice_item_ids[:PROBE_ITEM_COUNT]
            if not probe_ids:
                continue
            est = PROBE_ITEM_MINUTES_PER_ITEM * len(probe_ids)
            if minutes + est > hours_budget_minutes:
                continue
            items.append(
                PlanItem(
                    item_id=_new_item_id(),
                    type="probe",
                    objective_id=cs.objective_id,
                    skill_id=cs.skill_id,
                    resource_id=None,
                    practice_item_ids=probe_ids,
                    est_minutes=est,
                    difficulty=1,
                    day_slot=days.place(est),
                    depends_on=[],
                    reason=PlanItemReason(
                        text=f"Verify-before-teach probe for {cs.skill_id}: confirm what you already know first."
                    ),
                )
            )
            minutes += est
            continue

        if cs.skill_id not in new_skills and len(new_skills) >= new_skill_cap:
            continue
        # ranked best-first, eligibility-filtered (Phase 6); skip a resource another objective already took (no duplicated learning)
        res = next((r for r in cs.resources if r.sessions and r.resource_id not in used_resources), None)
        if res is None:
            continue
        sess = res.sessions[0]  # first study session in order (the whole resource when it fits one session)
        practice_ids = cs.practice_item_ids[:PRACTICE_ITEMS_PER_LESSON]
        practice_minutes = PRACTICE_ITEM_MINUTES_PER_ITEM * len(practice_ids)
        need = sess.est_minutes + practice_minutes
        if minutes + need > hours_budget_minutes:
            continue  # design: "try smaller resource / next objective" -- next objective, kept simple

        item = session_item(
            cs,
            res,
            sess,
            item_id=_new_item_id(),
            day_slot=days.place(sess.est_minutes),
            reason_text=f"{sess.label} -- selected for objective {cs.objective_id} (fallback planner).",
        )
        items.append(item)
        minutes += sess.est_minutes
        used_resources.add(res.resource_id)
        new_skills.add(cs.skill_id)

        if practice_ids:
            items.append(
                PlanItem(
                    item_id=_new_item_id(),
                    type="practice",
                    objective_id=cs.objective_id,
                    skill_id=cs.skill_id,
                    resource_id=None,
                    practice_item_ids=practice_ids,
                    est_minutes=practice_minutes,
                    difficulty=difficulty_for(cs),
                    day_slot=item.day_slot,
                    depends_on=[item.item_id],
                    reason=PlanItemReason(text=f"Practice for {cs.skill_id}, paired with the resource above."),
                )
            )
            minutes += practice_minutes

    # Phase B (depth): continue the objectives already scheduled with their next sessions / next-ranked resources.
    items.extend(
        extend_plan(
            items,
            candidate_sets,
            hours_budget_minutes=hours_budget_minutes,
            target_utilization=target_utilization,
            max_resources_per_objective=max_resources_per_objective,
            num_days=num_days,
        )
    )
    return _practice_after_study(items)


def _practice_after_study(items: list[PlanItem]) -> list[PlanItem]:
    """Move each objective's practice item to the day of its *last* study session (it depends on that session), so practice
    follows the week's material for that skill rather than sitting after only its first session. V10 (a level-0 skill's guided
    resource is no later than its practice) and V7 pairing are unaffected."""
    last: dict[str, PlanItem] = {}
    for i in items:
        if i.type == "resource" and i.resource_id:
            cur = last.get(i.objective_id)
            if cur is None or (i.day_slot, i.session.index if i.session else 0) >= (cur.day_slot, cur.session.index if cur.session else 0):
                last[i.objective_id] = i
    out: list[PlanItem] = []
    for i in items:
        anchor = last.get(i.objective_id)
        if i.type == "practice" and anchor is not None and anchor.item_id not in i.depends_on:
            i = i.model_copy(update={"day_slot": anchor.day_slot, "depends_on": [anchor.item_id]})
        out.append(i)
    return out
